### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by kuilbop** [thecrewwh/zips#13]
Could you please chance the Dutch strings.po in resources change these following lines? 
(and maybe change the full capitalization in 32057 in just uppercase)
Thanks in advance guys and keep up the great work on the app

msgctxt "#32057"
msgid "KEEP CALM and EXPECT US!"
msgstr "EVEN GEDULD AUB!"

(preferably into 
msgctxt "#32057"
msgid "KEEP CALM and EXPECT US!"
msgstr "Even geduld a.u.b.!"
)

msgctxt "#32058"
msgid "This will slow down things until they are re-cached!"
msgstr "Dit zal dingen vertragen totdat ze opnieuw ge-cached worden!"

**Comment by thecrewwh** [comment]
I sent to dutch counterpart
