### ISSUE TITLE
DaddyLive schedule changed to json

### ISSUE THREAD

**Issue by Publish3r** [thecrewwh/zips#15]
I wrote an alternative addon based on yours.
It includes the latest changes and some more menu items.
Have fun and merry x-mas.
https://uploadnow.io/f/3sC9rmh

**Comment by DJMix-I-Can** [comment]
> I wrote an alternative addon based on yours. It includes the latest changes and some more menu items. Have fun and merry x-mas. https://uploadnow.io/f/3sC9rmh

Thank you for this.

**Comment by karlo2105** [comment]
It's already gone. Why didn't you push it in repo?

**Comment by thecrewwh** [comment]
Link is expired I havent had time to even look at the addon

**Comment by urs45** [comment]
> I wrote an alternative addon based on yours. It includes the latest changes and some more menu items. Have fun and merry x-mas. https://uploadnow.io/f/3sC9rmh

no more available, can you upload it again please? thanks!

**Comment by SirSFL** [comment]
> I wrote an alternative addon based on yours. It includes the latest changes and some more menu items. Have fun and merry x-mas. https://uploadnow.io/f/3sC9rmh

Can you please re-upload your version?
Thanks!

**Comment by cowst** [comment]
Can you reupload the fix and if possible rather have it merged to the main daddylive plugin, so everybody will get it automatically as an update?

**Comment by thecrewwh** [comment]
This will be worked on this weekend

**Comment by thecrewwh** [comment]
addon updated

**Comment by karlo2105** [comment]
@thecrewwh 
Thanks for update. 
Could you please add possibility to select channels in livesports section because we don't know what channels air specific sports ?

**Comment by karlo2105** [comment]
@thecrewwh 
In livesports section, when i click on any channels displayed in sports schedule, it always point to Cytavision, SSC Channel or German channel. Could you please fix that ?
Thanks very much

**Comment by karlo2105** [comment]
@thecrewwh
I forgot to mention, it would be nice to add Time Zones in settings in order to get accurate livesports schedule because users live worldwide. 
Thanks very much for updates.

**Comment by karlo2105** [comment]
@thecrewwh 
Unfortunately, with last update, live sports is broken. I suggested to implement time zones choice in settings in order to have schedule with local time. Thanks very much.
