### ISSUE TITLE
DaddyLive some streams not working (AES 128 encrypted)

### ISSUE THREAD

**Issue by Publish3r** [thecrewwh/zips#16]
Hi.

DaddyLive's streams are more and more changing to AES 128 encryption (Player 1).
Kodi das not resolve and play it. I tried with ffmpeg and streamlink without success, too.

Maybe you can code resolvers for the streams that are provides with Player 2 and / or Player 3.
Those streams are not encrypted.

Thanks.

**Comment by thecrewwh** [comment]
> Hi.
> 
> DaddyLive's streams are more and more changing to AES 128 encryption (Player 1). Kodi das not resolve and play it. I tried with ffmpeg and streamlink without success, too.
> 
> Maybe you can code resolvers for the streams that are provides with Player 2 and / or Player 3. Those streams are not encrypted.
> 
> Thanks.

Yes that is not a issue I will when i get a chance can you re uload your fixes makes things faster I should have time this weekend  Also can you tell what channels are AES

**Comment by Publish3r** [comment]
Hi.

I uploaded my privat version again here: https://filebin.net/np7nq3mscj6qqp (expires in 6 days).
Example channels that AES encrypted: WWE Network & FOX USA.

My skills are not good enough to code resolver for the other players on the website.
If you can to it, i would suggest to write some resolver for the other players / streams and make an addon setting for changing the players / streams.

Thanks and good luck.
