### ISSUE TITLE
Daddylive : time zones

### ISSUE THREAD

**Issue by karlo2105** [thecrewwh/zips#17]
@thecrewwh
Thanks very much for fixing live sports section. Could you please switch default time zone to GMT instead of ET because it's easier to get orientation?
Best solution would be to implement custom time zone settings like [Daddylive website does](https://1.dlhd.sx/)
![IMG_20240414_101720](https://github.com/thecrewwh/zips/assets/5579457/1c15fad3-e36b-46ff-adc4-afa1f23c21cc)

**Comment by thecrewwh** [comment]
its already auto to local timezone

**Comment by karlo2105** [comment]
@thecrewwh 
Not really. I am situated in GMT+1 timezone. You can notice below that (GMT+7) is wrongly applied in continental Europe. 

Dadylive in Kodi 
![Daddylive timezone](https://github.com/user-attachments/assets/b36adede-aac2-4752-bf06-e92ce20fcab1)

[Daddy website](https://thedaddy.to/) set on GMT+1
![Screenshot 2024-11-25 at 15-17-46 DaddyLiveHD - Live Sp](https://github.com/user-attachments/assets/601fb2c2-f0e6-43e5-80f5-5841db537277)
