### ISSUE TITLE
A pull Request

### ISSUE THREAD

**Issue by azzy9** [thecrewwh/zips#5]
Plugin: plugin.video.pluto2tv V1.0.0
Kodi: 18.8

Hi,
I use the Pluto TV plugin but unfortunately the TV Guide on plugin gives an error when trying to load it.
I have fixed the issue for myself but would like to create a PR to submit the changes, but this repo only hosts the ZIPs.
Is there anywhere I could make the PR?

Many Thanks,

Azzy9

**Comment by thecrewwh** [comment]
I will ask the developer of this addon if he will allow that just for reference I am not seeing any issues using it

**Comment by azzy9** [comment]
Thank you for your reply.

The issue is that the Plutotv api doesn't like the datetime format provided, so it returns an error.

I have fixed it for me by modifying the results method in plugin.video.pluto2tv\resources\lib\uepgplutotv.py to:

```
def results():
    tz    = str(timezone())
    start = datetime.datetime.now().strftime('%Y-%m-%dT%H:00:00Z')
    stop  = (datetime.datetime.now() + datetime.timedelta(hours=6)).strftime('%Y-%m-%dT%H:00:00Z')
    return (BASE_GUIDE %(start,stop,'deviceId=%s&deviceMake=Chrome&deviceType=web&deviceVersion=80.0.3987.149&DNT=0&sid=%s&appName=web&appVersion=5.7.5-d60060c7283e0978cc63ba036956b5c1657f8eba'%(deviceId1,sid1)))
```
