### ISSUE TITLE
All 3 Links on everything dont play

### ISSUE THREAD

**Issue by ohmichael** [thecrewwh/zips#9]
tested to see if anything plays i got nothing.

**Comment by mrgsi** [comment]
All 3 Links? Are you talking about the source list after a scrape?

**Comment by ohmichael** [comment]
i figured it out sir its debrid only - since i do not have it yet it won't play links - but its a kool addon

**Comment by mrgsi** [comment]
I thought it might be that. Free links are getting harder and harder to use. If you can afford a debrid service (about $4/month) you would LOVE it. Tons of good quality HD links.
